name: Apply Terraform Changes to Auth0
on:
  push:
    branches:
      - main

env:
  TERRAFORM_VERSION: "latest"
  TERRAGRUNT_VERSION: "latest"
  TERRAFORM_WORKING_DIR: './terraform'

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: true 

      - name: Set Auth0 Credentials
        run: |
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> $GITHUB_ENV
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}" >> $GITHUB_ENV  
      
      # - name: Change Directory to Terraform
      #   run: cd terraform
          
      - name: Initialize Terraform
        run: terraform init
        # working-directory: terraform
        env:
          TF_LOG: DEBUG

      - name: Terraform Plan
        run: terraform plan
        # working-directory: terraform
        env:
          TF_LOG: DEBUG

      - name: Terraform Apply
        run: terraform apply -auto-approve
        # working-directory: terraform
        env:
          TF_LOG: DEBUG